### ISSUE TITLE
Cursor Locking

### ISSUE THREAD

**Issue by CodeChrisB** [markthomas007/Stanley-Parable-Ultra-Mod-Delux#1]
I know its mentioned in your  ReadMe

to fix this  you could make a own hotkey for this and then you call UnlockCursor() or however you want to call it. 

```
private void UnlockCursor(){
      Cursor.lockState =  CursorLockMode.None;
}
```
This should fix the problem.

**Comment by MarcellaVT** [comment]
This has actually been added in the last commit i did which was before this post. I made a toggle version instead which checks what the current lock state and does the opposite.
I've just been too busy with college finals to add a new release onto this github. Expect a new release soon. ill leave this open until that release is out. Thanks for the code anyway.

**Comment by MarcellaVT** [comment]
I have now released a new version that has this so this will now be closed.
