### ISSUE TITLE
Occlusion disabling is not working

### ISSUE THREAD

**Issue by catfueledmayhem** [markthomas007/Stanley-Parable-Ultra-Mod-Delux#2]
Just cant use occlusion disabling

**Comment by MarcellaVT** [comment]
Hey. Can you give more info? I have not put out occlusion disabling into a release yet. It should work if you build it yourself. Ive been busy lately and just have not put it into a release yet.

**Comment by catfueledmayhem** [comment]
Then why occlusion disabling is even an option?

чт, 9 июн. 2022 г. в 22:01, Markthomas007 ***@***.***>:

**Comment by MarcellaVT** [comment]
Try using the newest version that was just released. Let me know if it works.

**Comment by MarcellaVT** [comment]
No response so im just going to close this. Please reopen if you still have the problem.
